[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
day_21 = "3trupFmUjciD2oetaDnA9MjMgF32Cr1ZMSsaYg9qp6C7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
