[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_function_tutorial = "BsHEqRbo3rjsQJc8WsV5X5yWn2KcxvsnN2sK8yNxs5XQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
